export const kpiData = [
  {
    id: "total",
    icon: "biotech",
    label: "Total Examens",
    value: "1,284",
    badge: "+4%",
    badgeClass: "text-blue-600 bg-blue-50",
    iconClass: "text-primary bg-primary/10",
    valueClass: "text-on-surface",
  },
  {
    id: "stat",
    icon: "emergency",
    label: "En Attente STAT",
    value: "3",
    badge: "CRITIQUE",
    badgeClass: "text-tertiary bg-tertiary-fixed",
    iconClass: "text-tertiary bg-tertiary-container/20",
    valueClass: "text-tertiary",
  },
  {
    id: "tat",
    icon: "schedule",
    label: "Délai Moyen (TAT)",
    value: "2.4",
    valueSuffix: " jours",
    badge: null,
    badgeClass: "",
    iconClass: "text-secondary bg-secondary/10",
    valueClass: "text-on-surface",
  },
  {
    id: "validation",
    icon: "fact_check",
    label: "En Attente Validation",
    value: "12",
    badge: "12 Dossiers",
    badgeClass: "text-on-surface-variant bg-surface-container",
    iconClass: "text-primary bg-primary/10",
    valueClass: "text-on-surface",
  },
];

export const weeklyData = [
  { day: "Lun", value: 142, heightPercent: 60 },
  { day: "Mar", value: 185, heightPercent: 85 },
  { day: "Mer", value: 98, heightPercent: 45 },
  { day: "Jeu", value: 156, heightPercent: 70 },
  { day: "Ven", value: 210, heightPercent: 95, highlighted: true },
  { day: "Sam", value: 45, heightPercent: 30 },
  { day: "Dim", value: 22, heightPercent: 20 },
];

export const urgentSnippetData = [
  {
    id: 1,
    nom: "DUPONT Jean",
    type: "Biopsie Hépatique",
    temps: "12m",
    urgence: "critique",
  },
  {
    id: 2,
    nom: "MOREL Sophie",
    type: "Exérèse Cutanée",
    temps: "45m",
    urgence: "critique",
  },
  {
    id: 3,
    nom: "LEFEBVRE Paul",
    type: "Cytologie Liquide",
    temps: "1h 10m",
    urgence: "semi",
  },
  {
    id: 4,
    nom: "GARCIA Elena",
    type: "Biopsie Gastrique",
    temps: "2h 30m",
    urgence: "semi",
  },
];

export const urgentTableData = [
  {
    id: "#2023-9842",
    initiales: "JD",
    patient: "Jean DUPONT",
    examen: "Biopsie Hépatique (Urgente)",
    statut: "EN COURS - STAT",
    statutType: "stat",
    temps: "12 minutes",
  },
  {
    id: "#2023-9845",
    initiales: "SM",
    patient: "Sophie MOREL",
    examen: "Exérèse Cutanée (Urgente)",
    statut: "EN COURS - STAT",
    statutType: "stat",
    temps: "45 minutes",
  },
  {
    id: "#2023-9848",
    initiales: "LP",
    patient: "Paul LEFEBVRE",
    examen: "Cytologie Liquide (Semi-Urgente)",
    statut: "PRE-ANALYSE",
    statutType: "secondary",
    temps: "1h 10m",
  },
  {
    id: "#2023-9851",
    initiales: "EG",
    patient: "Elena GARCIA",
    examen: "Biopsie Gastrique",
    statut: "EN ATTENTE",
    statutType: "secondary",
    temps: "2h 30m",
  },
  {
    id: "#2023-9854",
    initiales: "MK",
    patient: "Marc KOWALSKI",
    examen: "Examen d'Extemporanée",
    statut: "BLOQUE - TECH",
    statutType: "primary",
    temps: "4h 15m",
  },
];
